#!/usr/bin/env bash
#######################################################################
#                       Run MOLSIM in parallel                        #
#######################################################################
set -euo pipefail

#*************************************************************
#*      Start of definition section                          *
#*************************************************************
bin=

#*************************************************************
#*                  Architecture                             *
#*************************************************************
ARCH=LOCAL_INTEL
#ARCH=ALARIK_INTEL

echo
echo '--------------------------------------'
echo "  Start of molsim_par, Arguments: $@"
echo '--------------------------------------'
echo
date

echo
echo 'Execute'
echo

if test $ARCH = LOCAL_INTEL
then
if (( $# < 2 ))
then
   echo "syntax: molsim_par job cores"
   exit 1
fi
   mpiexec -np ${@: -1} $bin/molsim_par.exe "${@:1:$(($#-1))}"
fi
if test $ARCH = ALARIK_INTEL
then
    mpiexec -bind-to-core $bin/molsim_par.exe "$@"
fi

date
echo
echo '--------------------------------------'
echo "   End of molsim_par, Arguments: $@"
echo '--------------------------------------'
echo
