#!/usr/bin/env bash
#######################################################################
#                       Run MOLSIM in serial                          #
#######################################################################
set -euo pipefail

#*************************************************************
#*      Start of definition section                          *
#*************************************************************
bin=

#*************************************************************
#*                  Architecture                             *
#*************************************************************
ARCH=LOCAL_INTEL
#ARCH=ALARIK_INTEL

if [ $# -eq 0 ]; then
    echo "No arguments provided"
    exit 1
fi

echo
echo '--------------------------------------'
echo "  Start of molsim_ser, Arguments: $@"
echo '--------------------------------------'
echo
date

echo
echo 'Execute'
echo

$bin/molsim_ser.exe "$@"

date
echo
echo '--------------------------------------'
echo "   End of molsim_ser, Arguments: $@"
echo '--------------------------------------'
echo
